resolver: lts-21.7 # 2023-08-14, GHC 9.4.5

nix:
  packages:
    - pcre
    - pkgconfig
    - postgresql
    - zlib
  # disable pure by default so that the test enviroment can be passed
  pure: false
extra-deps:
  - configurator-pg-0.2.7
  - fuzzyset-0.3.1
  - hasql-notifications-0.2.0.6
  - hasql-pool-0.10
  - megaparsec-9.2.2
  - cryptostore-0.3.0.1
  #- wai-saml2 # to load this module from the local filesystem;
  - git: https://github.com/Gab0/wai-saml2.git
    commit: f2d4cc5a8b4dd1615b5bf03ef8713fa6ebff8f8d
  - postgresql-libpq-0.10.0.0
